name: CI
on:
  push:
    branches:
      main
  pull_request:

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code
        run: |
          make build-linux

      - name: Run code
        run: |
          ./armstrong_linux_amd64
